# report_composer.py
#
# Copyright 2025 Vladimir Kosolapov
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later

from gi.repository import Gio, GLib
from ..vt_provider import FileAnalysis, URLAnalysis

class ReportComposer:
    def format_section(self, title, items):
        return [f"=== {title} ==="] + [
            f"{key}: {value}" for key, value in items if value
        ]

    def generate_report(self, analysis):
        if not analysis:
            return ""

        sections = []

        header = f"{_('Generated by Lenspect - VirusTotal Scanner for Linux')}"
        sections.append([header])

        if isinstance(analysis, FileAnalysis):
            sections.append(self.format_section(_('File Information'), [
                (_('Filename'), analysis.file_name),
                (_('Known Filename'), analysis.meaningful_name),
                (_('Size'), analysis.formatted_size),
                (_('Type'), analysis.file_type),
                (_('First Submission'), analysis.first_submission_date),
                (_('Last Analysis'), analysis.last_analysis_date),
                (_('Times Submitted'), str(analysis.times_submitted)),
                *analysis.get_hashes(),
            ]))

        elif isinstance(analysis, URLAnalysis):
            sections.append(self.format_section(_('URL Information'), [
                (_('URL'), analysis.url),
                (_('Title'), analysis.title),
                (_('Final URL'), analysis.final_url),
                (_('First Submission'), analysis.first_submission_date),
                (_('Last Analysis'), analysis.last_analysis_date),
                (_('Times Submitted'), str(analysis.times_submitted)),
                (_('Community Score'), str(analysis.community_score)),
            ]))

            redirect_chain = analysis.get_redirect_chain()
            if redirect_chain:
                if redirect_chain[0].rstrip('/') == analysis.url.rstrip('/'):
                    redirect_chain = redirect_chain[1:]
                if redirect_chain:
                    sections.append(self.format_section(_('Redirection Chain'), [
                        (f"{_('Redirect')} {i+1}", url)
                        for i, url in enumerate(redirect_chain)
                    ]))

            categories = analysis.get_categories()
            if categories:
                sections.append(self.format_section(_('Categories'), sorted(
                    categories.items(), key=lambda x: x[0].lower())))

        sections.append(self.format_section(_('Detection Statistics'), [
            (_('Malicious'), str(analysis.malicious_count)),
            (_('Suspicious'), str(analysis.suspicious_count)),
            (_('Clean'), str(analysis.harmless_count)),
            (_('Undetected'), str(analysis.undetected_count)),
            (_('Total Vendors'), str(analysis.total_vendors)),
        ]))

        if analysis.threat_count > 0:
            detections = analysis.get_detections()
            if detections:
                sections.append(self.format_section(_('Threat Detections'), sorted(
                    detections.items(), key=lambda x: x[0].lower())))

        return "\n\n".join("\n".join(section) for section in sections)

    def generate_filename(self):
        timestamp = GLib.DateTime.new_now_local().format("%Y%m%d_%H%M%S")
        return f"lenspect_{timestamp}.txt"

    def save_to_file(self, report_text: str, file_path: str):
        try:
            gfile = Gio.File.new_for_path(file_path)
            gfile.replace_contents(
                report_text.encode("utf-8"), None, False,
                Gio.FileCreateFlags.NONE, None)
            return True
        except GLib.Error:
            return False
